### ISSUE TITLE
Mod doesnt do anything on cracked among us

### ISSUE THREAD

**Issue by jsm-10-ctrl** [Gurge44/EndlessHostRoles#118]
I have a cracked version of among us that i got from steamrip and after I installed the mod the game still loads up as vanilla

**Comment by Gurge44** [comment]
And how is it my problem that you can't spend $2 to buy Among Us?

**Comment by Tommy-XL** [comment]
lol

**Comment by Ultradragon005** [comment]
![image](https://c.tenor.com/spJePCsFHlEAAAAd/tenor.gif)
