### ISSUE TITLE
[FR] Add new settings for Sheriff and doctor

### ISSUE THREAD

**Issue by VixenSugo** [Gurge44/EndlessHostRoles#130]
- Sheriff: He should not be able to use sabotage and doors

- Doctor: The doctor can anonymously chat with the players in the meeting and announce the cause of death. quick chat and free chat.

You can change two of the game's default chats with bite or kill options for the role of the doctor. so that when the doctor selects certain text shortcuts in quick chat, the bite or kill message will be sent in the form of a system message or host message in the chat section.
In this case, in games where evil gusser is present or not, they cannot guess or kill the doctor quickly. For free chat, you can use commands similar to guessers

**Comment by HyperAtill** [comment]
> - Sheriff: He should not be able to use sabotage and doors
> 
> - Doctor: The doctor can anonymously chat with the players in the meeting and announce the cause of death. quick chat and free chat.
> 
> You can change two of the game's default chats with bite or kill options for the role of the doctor. so that when the doctor selects certain text shortcuts in quick chat, the bite or kill message will be sent in the form of a system message or host message in the chat section.
> In this case, in games where evil gusser is present or not, they cannot guess or kill the doctor quickly. For free chat, you can use commands similar to guessers

Unfortunately, we don't know who attempts to close doors. This means we can disable closing doors completely but cannot for a specific player
