### ISSUE TITLE
wtf why isnt any sservers poppin up is this mod broken?

### ISSUE THREAD

**Issue by zakiboy979** [Gurge44/EndlessHostRoles#166]
i cant joni any servers

**Comment by zakiboy979** [comment]
CAN SOMEONE HELP ME?

**Comment by HyperAtill** [comment]
> i cant joni any servers

Hi

Maybe your region is wrong if you can't join
Switch it to normal Europe/North America/Asia

If you're talking about joining lobbies in public lobbies list, then it means that no one is hosting right now, or if someone is hosting, they have a private lobby

**Comment by HyperAtill** [comment]
> CAN SOMEONE HELP ME?

Bruh, man, we can't do anything after 1 second after you sent a message
We aren't superheroes, we are humans
