### ISSUE TITLE
help

### ISSUE THREAD

**Issue by xzilentx** [Gurge44/EndlessHostRoles#169]
cant add [MalumMenu]. if i add the plugin the game is going to vanilla

**Comment by Dxgamer7405** [comment]
whats your friend code? we need the friend code to enable the malum menu for you

**Comment by xzilentx** [comment]
i dont know what you mean, so i give you the link,  
https://github.com/scp222thj/MalumMenu

**Comment by Dxgamer7405** [comment]
![image](https://github.com/user-attachments/assets/dceed965-ca16-4ed7-bc13-b6a06dc7ded8)
check main menu and click here
