### ISSUE TITLE
black screen issue

### ISSUE THREAD

**Issue by vijenderyadav944** [Gurge44/EndlessHostRoles#172]
I am hosting the game and when my friends join and I start the game, their screen gets stuck at dark screen. and nothing loads, I always gets the imposter in this case and the others just stay still. Why is this happening as this is a host-only mod, Right?

**Comment by vijenderyadav944** [comment]
Nothing at all was showing the screen of others, I was the only one entering the game. They are able to see the modded lobby in the spacecraft and check the roles as well.

**Comment by Joelbobby** [comment]
Yes i am also facing this issue, some of my friends are able to join while a few others get a black screen.

**Comment by Joelbobby** [comment]
> Nothing at all was showing the screen of others, I was the only one entering the game. They are able to see the modded lobby in the spacecraft and check the roles as well.

My issue was solved when i stopped using the roles which required the members to have a "**pet**". I believe it mustnt be used unless all the members have a pet, or else those who get such roles may get a blank screen
