### ISSUE TITLE
cant use melum menu with erh friend code hookedbye#5905

### ISSUE THREAD

**Issue by readytothrow** [Gurge44/EndlessHostRoles#189]

**Comment by Tommy-XL** [comment]
This bro immediately send his friend code so that he could be banned, conveniently

**Comment by Tommy-XL** [comment]
lmao

**Comment by HyperAtill** [comment]
> lmao

I'm really interested for what he can use Malum Menu **with** EHR installed on 1 client

**Comment by Gurge44** [comment]
Plan succeeded

**Comment by readytothrow** [comment]
oh no i m so scared to get banned oh noo

**Comment by Gurge44** [comment]
can you also send your hashed puid, just curious?

**Comment by HyperAtill** [comment]
> oh no i m so scared to get banned oh noo

So, hacking or testing? fyi testing is actually a possible variant... or I'm too friendly...

**Comment by Gurge44** [comment]
> > oh no i m so scared to get banned oh noo
> 
> So, hacking or testing? fyi testing is actually a possible variant... or I'm too friendly...

well we don't know what mod is `erh`

**Comment by readytothrow** [comment]
i dont care to cheat in among us i only use unlock cosmetics

**Comment by HyperAtill** [comment]
> i dont care to cheat in among us i only use unlock cosmetics

https://github.com/astra1dev/AUnlocker
This works with EHR

**Comment by Gurge44** [comment]
Yes, if you want that, use AUnlocker
It's far less of a cheat than MM
