### ISSUE TITLE
new bug

### ISSUE THREAD

**Issue by jiggusuperking** [Gurge44/EndlessHostRoles#82]
what is this bug on vanilla servers
pls remove this bug 
bug:
an unknown error make you disconnected from the server 
or
if you not removing bug i hate this mod

**Comment by HyperAtill** [comment]
> what is this bug on vanilla servers pls remove this bug bug: an unknown error make you disconnected from the server or if you not removing bug i hate this mod

Do you have logs or something that can show us when and why this bug happens?
Otherwise it is unfixable

**Comment by Tommy-XL** [comment]
It's funny that he says that he will hate this mod, although he himself did not provide logs and did not say exactly when this usually happens, lol

**Comment by Tommy-XL** [comment]
Nice logic

**Comment by Gurge44** [comment]
The funniest thing is it's probably user error (like weak or slow internet) too

**Comment by Ultradragon005** [comment]
> what is this bug on vanilla servers pls remove this bug bug: an unknown error make you disconnected from the server or if you not removing bug i hate this mod

probably has something to do with skill issue, see if resolving that fixes the problem

**Comment by Gurge44** [comment]
Who wants to bet that they didn't even check the response on this issue?

**Comment by GameTechGuides** [comment]
Internet issue the mod work very well

**Comment by PHGaming121** [comment]
> Internet issue the mod work very well

arent u the guy who is trying to make github builds for submerged?

**Comment by GameTechGuides** [comment]
> > Internet issue the mod work very well
> 
> arent u the guy who is trying to make github builds for submerged? (or something like that)

yes i make the github builds but i will rewrite that
